### ISSUE TITLE
Maria Walston is still having problems having her votes count/be recorded.

### ISSUE THREAD

**Issue by rkavalhuna** [jfrabell/CASRS#25]

**Comment by jfrabell** [comment]
Is there any chance I can get an example of which report and which causal factors were causing the problem?

**Comment by rkavalhuna** [comment]
Maria,

Can you give Jeff this information?

Russ Kavalhuna
Executive Director of Flight Operations
Western Michigan University
College of Aviation
269.377.5031

On Apr 5, 2017, at 11:04 AM, Jeff Frabell <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there any chance I can get an example of which report and which causal factors were causing the problem?

**Comment by rkavalhuna** [comment]
Jeff,

The reports that I had a problem with this week were, 17-059 and 27-068. Below is what I was trying to vote for each report. Also when I click on report ID, it does not show me what was previously voted, I have to revote and make another full submission.

68: Weather and Attention to detail: Red
59: Personal Stress: Green

Have a good weekend.


Maria Walston

Western Michigan University

248-410-3389

maria.c.walston@wmich.edu

________________________________

**Comment by jfrabell** [comment]
Sorry for the delay.  The reports you mentioned had disagreement on the risk level.  They kicked back as disagreement because of this.  When users disagree on reports, the system gives another chance to review the reports to both users.  Your previous selections are not displayed to you by design.  The idea was reviewers would look a second time with fresh eyes and possibly come to agreement.  

If the College as a whole would like to change the system to show you what you voted for the first time, I can make that change.  

Let me know, Russ.
